<?php 

return [
  'title' => 'Chi Siamo',
  'subtitle' => 'Storia',
  '2003' => 'La ricerca formale sulle reti ad hoc ha iniziato nel dipartimento Sistemi dell`Universidad Nacional - Colombia - Sede Bogotá, nell`ambito del Master in Ingegneria delle Telecomunicazioni, questa ricerca è nata dal lavoro del Professor Jorge Eduardo Ortiz e l`ingegnere  Jaime Leonardo Bobadilla Molina, con il lavoro da sistemi dinamici e stocastici, come reti ad hoc e il impatto sulle telecomunicazioni wireless. Come risultato di questo processo, iniziano a essere pubblicati lavori relativi a modelli di mobilità e protocolli di routing.',
  '2014' => 'A causa di un numero rappresentativo di lavori diretti su reti ad hoc, reti mesh e reti di sensori, il professor Jorge Eduardo Ortiz, prende l`iniziativa di riunire i suoi studenti universitari e laureati, per invitarli a formare un nuovo gruppo di ricerca, in questo come nasce il gruppo TLÖN - Gruppo di ricerca in reti di telecomunicazioni dinamiche e linguaggi di programmazione distribuiti, orientato alla ricerca sulle basi filosofiche e teoriche dei sistemi distribuiti su reti ad hoc, con un approccio sociale ispirato, convalidando le metodologie per la loro attuazione e sviluppo. Durante quest`anno c`è la creazione e la registrazione nell Sistema de Gestione della  Ricerca  - Hermes dalla Universidad Nacional Sede Bogotá. Abbiamo partecipato a eventi di divulgazione scientifica.',
  '2015' => ' Dopo di fare il processo  e documentazione  richiesta per la Vicedecanatura di Ricerca e Extensión della Scuola di Ingegneria, il gruppo di ricerca ha ottenuto la garanzia della  Universidad Nacional de Colombia, come gruppo di ricerca,  Scontando i progetti di ricerca, le pubblicazioni, i membri e altri requisiti richiesti dall`università per detenere le categorie del gruppo di ricerca. Abbiamo partecipato a eventi di divulgazione scientifica e finito tesi di laurea e master.',
  '2016' => ' Si hanno fatto le prime indagini di Dottoratto nell progetto principale del Gruppo, chiamato Progetto TLÖN, le proposte sono stati approvati e si fa la presentazion del modello sociale ispirato come base della computazione distribuita wireless proposta. In questo momento, il gruppo ha quattro dottorandi, nove studenti del Master e 10 studenti di laurea. '
];