<?php 

return [
  'title' => 'About Us',
  'subtitle' => 'History',
  '2003' => 'Formal research on Ad-hoc networks begins in the Systems department of the National University of Colombia – Headquarters Bogotá, within the framework of the Master\'s Degree in Telecommunications Engineering, this research was born from the work of Professor Jorge Eduardo Ortiz and engineer Jaime Leonardo Bobadilla Molina in dynamic and stochastic systems, such as ad hoc networks and their impact on wireless telecommunications. Projects related to mobility models and routing protocols begin to be published as a result of this process.',
  '2014' => 'Due to a representative number of directed work on Ad Hoc, Mesh and sensor networks, Professor Jorge Eduardo Ortiz takes the initiative to bring together his undergraduate and graduate students, to invite them to form a new research group, this way the group was born TL-N - Research Group on Dynamic Telecommunications Networks & Distributed Programming Languages, oriented to research the philosophical and theoretical foundations of Distributed Systems on Ad Hoc Networks, with a focus validate the methodologies for its implementation and development. During this year the creation and registration in the Research Management System - Hermes of the National University of Bogotá is held. The group participated in scientific outreach events. ',
  '2015' => 'After performing the defined process and documentation requested by the Research and Extension Sub-Management of the Faculty of Engineering, the research group obtains the recognition of the National University of Colombia, as a research group , complying with the research projects, publications, members and other requirements required by the university to hold the research category and group. The group participated in scientific outreach events and graduate and postgraduate theses were completed.',
  '2016' => 'The first Doctoral projects of the Group\'s main project, called the TLÖN Project, are presented, which are approved and the proposal of the social model inspired as the basis of the wireless distributed computing proposed in this project is presented. At the moment the group has four PhD students, nine master\'s students, and 10 undergraduate students.'
];