<?php 

return [
  'title' => 'TLÖN Project',
  'subtitle' => 'Social Model',
  'figure' => 'Figure 1.',
  'figure-description' => 'Social model.',
  'description-1' => 'The Research Group on Dynamic Telecommunications Networks and Distributed Programming Languages - TLÖN proposes a computer scheme inspired by Social models, unfeasible in practice but possible in controlled artificial environments, this system is based on the concepts of Jhon Justice Rawls, Immanence of Baruch de Spinoza, Paradigm Thomas Kuhn, State Thomas Hobbes and the conceptions of existence and essence of Jean Paul Sartre, these elements must be reflected in computational abstractions for their most basic deployment, the objective is to find a complete analogy of a wireless virtualization scheme, necessary to implement these social models in computer systems, these principles are described in the figure. This inspired social model, is an abstraction superior to bio-inspired models, where it is possible to observe the components of the proposed model, which will also work over an Ad Hoc network, with all of its dynamic, stochastic and wireless conditions.',
  'description-2' => 'Within the general scheme of the proposal, an element capable of integrating multi-agent systems with virtualization is incorporated, with the behavior of an Ad Hoc network and the needs of services, for example in emergency situations. This container element of the system is a Programming Language, which basically takes a high level language and turns it into an understandable language for machines, which is a low level language, some basic prototypes of languages for agents have been developed but with clear limitations in performance or actions that do not require an analysis or a high computational component.',
  'description-3' => 'The best way to show the dimensions of the TLÖN project is through a layer model as seen in the figure of TLÖN System, in the first one is the infrastructure, where the ad hoc network is located, the second layer contains the wireless virtualization and the Operating System, in third place there is the Multiagent system, where communities of agents that provide services throughout the ad hoc network will operate in the virtualization scheme and finally a layer of specific applications from the computing system. Transversely there is the system language and its own ontology, generating the interactions in all of the model\'s layers.'
];