<?php 

return [
  'title' => 'Proyecto TLÖN',
  'subtitle' => 'Modelo Social',
  'figure' => 'Figura 1.',
  'figure-description' => 'Modelo social.',
  'description-1' => 'El proyecto del Grupo de investigación en redes de Telecomunicaciones Dinámicas y Lenguajes de Programación Distribuidos – TLÖN, propone un esquema de computación inspirado en modelos Sociales, inviables en la práctica pero posibles en entornos artificiales controlados, este sistema basado en los conceptos de Justicia de Jhon Rawls, Inmanencia de Baruch de Spinoza, Paradigma Thomas Kuhn, Estado Thomas Hobbes y las concepciones de existencia y esencia de Jean Paul Sartre, estos elementos deben reflejarse en abstracciones computacionales para su despliegue más básico, el objetivo es encontrar una analogía completa de un esquema de virtualización inalámbrica, necesaria para implementar estos modelos sociales en sistemas computacionales estos principios se ven descritos en la figura Este modelo social inspirado, es una abstracción superior a los modelos bio-inspirados, se pueden observar los componentes del modelo propuesto, el cual además funcionará sobre una red Ad Hoc con todas sus condiciones dinámicas, estocásticas e inalámbricas.',
  'description-2' => 'Dentro del esquema general de la propuesta se incorpora un elemento capaz de integrar los sistemas multiagente con la virtualización, con el comportamiento de una red Ad Hoc y las necesidades de servicios, por ejemplo en situaciones de emergencia. Este elemento contenedor del sistema es un Lenguaje de Programación, que básicamente lo que hace es tomar un lenguaje de alto nivel y convertirlo en un lenguaje entendible para las máquinas, es decir un lenguaje de bajo nivel, algunos prototipos básicos de lenguajes para agentes han sido realizados pero con limitaciones claras en rendimiento o acciones que no requieren un análisis ni un componente computacional alto.',
  'description-3' => 'La mejor forma de mostrar las dimensiones del proyecto TLÖN es por medio de un modelo de capas como se ve en la figura del Sistema TLÖN, en la primera esta la infraestructura, donde se encuentra la red ad hoc, la segunda capa contiene la virtualización inalámbrica y el Sistema Operativo, en tercer lugar se cuenta con el sistema Multiagente, donde operaran comunidades de agentes que proveerán servicios a lo largo de la red ad hoc en el esquema de virtualización y finalmente una capa de aplicaciones especificas del sistema de cómputo. De forma transversal se tiene el lenguaje del sistema y la ontología propia del mismo, generando las interacciones en todas las capas del modelo.'
];