<?php 

return [
  'title' => 'Acerca de Nosotros',
  'subtitle' => 'Historia',
  '2003' => 'Inicia la investigación formal sobre redes Ad-hoc en el departamento de Sistemas de la Universidad Nacional de Colombia – Sede Bogotá, en el marco de la Maestría en Ingeniería de Telecomunicaciones, esta investigación nace a partir de los trabajos del profesor Jorge Eduardo Ortiz y el ingeniero Jaime Leonardo Bobadilla Molina en sistemas dinámicos y estocásticos, como las redes ad hoc y su impacto en las telecomunicaciones inalámbricas. Como resultado de este proceso se empiezan a publicar trabajos relacionados con modelos de movilidad y protocolos de enrutamiento.',
  '2014' => 'Debido a un número representativo de trabajos dirigidos sobre redes ad hoc, redes Mesh y redes de sensores, el profesor Jorge Eduardo Ortiz, toma la iniciativa de reunir a sus estudiantes de pregrado y posgrado, para invitarlos conformar un nuevo grupo de investigación, de esta manera nace el grupo TLÖN - Grupo de investigación en redes de Telecomunicaciones Dinámicas & Lenguajes de Programación Distribuidos, orientado a la investigación de los fundamentos filosóficos y teóricos de Sistemas Distribuidos sobre redes Ad Hoc, con un enfoque social inspirado, validando las metodologías para su implementación y desarrollo. Durante este año se da la creación y registro en el Sistema de Gestión de la Investigación  - Hermes de la Universidad Nacional sede Bogotá. Se participó en eventos de divulgación científica.',
  '2015' => 'Después de realizar el proceso definido y la documentación solicitada por la Vicedecanatura de Investigación y Extensión de la Facultad de Ingeniería, El grupo de investigación obtiene el Aval de la Universidad Nacional de Colombia, como grupo de investigación, cumpliendo con los proyectos de investigación, publicaciones, miembros y demás requisitos exigidos por la universidad para ostentar la categorías e grupo de investigación. Se participó en eventos de divulgación científica y se finalizaron tesis de pregrado y posgrado.',
  '2016' => 'Se presentan los primeros proyectos de Doctorado del proyecto principal del Grupo, denominado Proyecto TLÖN, los cuales son aprobados y se presenta la propuesta del modelo social inspirado como base de la computación distribuida inalámbrica propuesta en este proyecto. En este momento el grupo cuenta con cuatro estudiantes de Doctorado, nueve estudiantes de maestría, y 10 de pregrado.'
];